server:
  port: 8080
cc:
  jwt:
    location: classpath:ccmall.jks
    alias: ccmall
    password: ccmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**