server:
  port: 8081

cc:
  jwt:
    location: classpath:ccmall.jks
    alias: ccmall
    password: ccmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
  db:
    database: cc-user


knife4j:
  enable: true
  openapi:
    title: "用户服务接口文档"
    description: "用户服务接口文档"
    email: 906713420@qq.com
    concat: pynobug
    url: https://www.cc.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.cc.user.controller